import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { Quicksand } from 'next/font/google'

const quicksand = Quicksand({display: 'auto', weight: ['600',"700","500"], subsets: ['latin-ext']})

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Qual</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`flex bg-white ${quicksand.className}`}>
        <aside className="relative flex w-20 bg-[#FFEC8A]">
          <ul className="absolute top-1/2 flex h-fit w-full -translate-y-1/2 -rotate-90 justify-center gap-4">
            <li>
              <Link href="#">
                <span className="flex whitespace-nowrap">Tentang kami</span>
              </Link>
            </li>

            <li>
              <Link href="#">
                <span className="flex whitespace-nowrap">Bantuan</span>
              </Link>
            </li>
          </ul>
        </aside>
        <div>
          <header></header>
          <main className="flex min-h-screen flex-col items-center justify-center"></main>
        </div>
      </div>
    </>
  );
};

export default Home;
