name: Node CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: executing remote ssh commands using private key
      uses: appleboy/ssh-action@v1.0.0
      with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/qual-mono
            git pull origin main
            git status
            pnpm install
            pnpm build
            pm2 reload qual-tech
            pm2 restart qual-tech